In [19]:
from utils import TextProcess

In [4]:
embed_size = 128    #Input features to the LSTM
hidden_size = 1024  #Number of LSTM units
num_layers = 1
num_epochs = 20
batch_size = 20
timesteps = 30
learning_rate = 0.002

In [5]:
corpus = TextProcess()

In [10]:
rep_tensor = corpus.get_data('alice.txt', batch_size=batch_size)

In [11]:
rep_tensor.shape

torch.Size([20, 1652])

In [12]:
vocab_size = len(corpus.dictionary)

In [13]:
vocab_size

5995

In [16]:
numb_batches = rep_tensor.shape[1]// timesteps
print(numb_batches)

55


In [21]:
import torch
import torch.nn as nn
lstm = nn.LSTM(3, 3)  # Input dim is 3, output dim is 
inputs = [torch.randn(1, 3) for _ in range(5)]  # make a sequence of length 5

In [23]:
inputs

[tensor([[ 0.8542, -1.0592, -0.1169]]),
 tensor([[ 0.6446, -0.9243,  1.5556]]),
 tensor([[-0.2512,  0.8041,  0.1951]]),
 tensor([[-0.7416, -0.1468, -0.1785]]),
 tensor([[ 0.0735,  0.3029, -0.2486]])]

In [24]:
hidden = (torch.randn(1, 1, 3),
          torch.randn(1, 1, 3))


In [25]:
hidden

(tensor([[[-0.6229, -2.0882,  0.6759]]]), tensor([[[0.1504, 0.7343, 1.0617]]]))

In [26]:
inputs

[tensor([[ 0.8542, -1.0592, -0.1169]]),
 tensor([[ 0.6446, -0.9243,  1.5556]]),
 tensor([[-0.2512,  0.8041,  0.1951]]),
 tensor([[-0.7416, -0.1468, -0.1785]]),
 tensor([[ 0.0735,  0.3029, -0.2486]])]

In [27]:
inputs = torch.cat(inputs).view(len(inputs), 1, -1)

In [29]:
inputs

tensor([[[ 0.8542, -1.0592, -0.1169]],

        [[ 0.6446, -0.9243,  1.5556]],

        [[-0.2512,  0.8041,  0.1951]],

        [[-0.7416, -0.1468, -0.1785]],

        [[ 0.0735,  0.3029, -0.2486]]])

In [30]:
hidden = (torch.randn(1, 1, 3), torch.randn(1, 1, 3))  # clean out hidden state
print(hidden)

(tensor([[[-0.2406,  0.6907,  0.6049]]]), tensor([[[-0.7746,  0.1242, -2.0568]]]))


In [32]:
inputs.shape

torch.Size([5, 1, 3])

In [42]:
aa = torch.rand([3, 6])

In [43]:
aa

tensor([[0.0219, 0.3380, 0.3213, 0.5592, 0.4122, 0.1848],
        [0.7897, 0.8225, 0.2011, 0.9238, 0.7943, 0.3689],
        [0.5813, 0.5204, 0.6841, 0.9158, 0.7132, 0.0297]])

In [40]:
aa.reshape(2, 9)

tensor([[0.7423, 0.2596, 0.0986, 0.5704, 0.6428, 0.6276, 0.7895, 0.6639, 0.5449],
        [0.4265, 0.4392, 0.4035, 0.0960, 0.6433, 0.3258, 0.2436, 0.7280, 0.7474]])

In [44]:
aa.reshape(9,2)

tensor([[0.0219, 0.3380],
        [0.3213, 0.5592],
        [0.4122, 0.1848],
        [0.7897, 0.8225],
        [0.2011, 0.9238],
        [0.7943, 0.3689],
        [0.5813, 0.5204],
        [0.6841, 0.9158],
        [0.7132, 0.0297]])

In [46]:
aa.reshape(-1)

tensor([0.0219, 0.3380, 0.3213, 0.5592, 0.4122, 0.1848, 0.7897, 0.8225, 0.2011,
        0.9238, 0.7943, 0.3689, 0.5813, 0.5204, 0.6841, 0.9158, 0.7132, 0.0297])

In [47]:
aa

tensor([[0.0219, 0.3380, 0.3213, 0.5592, 0.4122, 0.1848],
        [0.7897, 0.8225, 0.2011, 0.9238, 0.7943, 0.3689],
        [0.5813, 0.5204, 0.6841, 0.9158, 0.7132, 0.0297]])