In [1]:
import torch

In [2]:
import torchvision

In [3]:
torch.cuda.is_available()

False

In [4]:
a = torch.tensor([2, 2, 1])

In [5]:
print(a)

tensor([2, 2, 1])


In [6]:
b = torch.tensor([[2,1,5], [1, 1,3]])
print(b)

tensor([[2, 1, 5],
        [1, 1, 3]])


In [8]:
a.shape

torch.Size([3])

In [9]:
a.size()

torch.Size([3])

In [11]:
c = torch.FloatTensor([[1,2,3], [1, 2, 2]])

In [12]:
print(c)

tensor([[1., 2., 3.],
        [1., 2., 2.]])


In [13]:
b = torch.Tensor([[1,2,3], [4,5,6], [7,8,9]])
print(b)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [14]:
b.view(-1,1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [15]:
print(b)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [17]:
b.view(9)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [19]:
b.view(-1, 3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [20]:
r2 = torch.randn(4, 4)

In [21]:
print(r2)

tensor([[-0.8455,  0.6394, -0.8890,  1.0233],
        [-0.8446, -0.3681, -0.5056,  0.4564],
        [ 0.7331, -0.8230, -1.2595, -1.5440],
        [ 0.7407, -0.0175, -0.8269, -0.7835]])


In [22]:
print(r2.dtype)

torch.float32


In [23]:
in_array = torch.randint(6, 10, (5,))

In [24]:
print(in_array)

tensor([8., 9., 9., 6., 6.])


In [25]:
print(in_array.dtype)

torch.float32


In [3]:
z = torch.zeros(3,3, dtype=torch.long)
print(z)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [4]:
import sys
print(sys.verion)

AttributeError: module 'sys' has no attribute 'verion'

In [5]:
import sys

In [6]:
print(sys.version)

3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]


In [7]:
a = torch.ones(5)

In [8]:
print(a)

tensor([1., 1., 1., 1., 1.])


In [9]:
b = a.numpy()

In [10]:
print(b)

[1. 1. 1. 1. 1.]


In [11]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [19]:
a = torch.ones(5)
b = a.numpy()
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [21]:
first_1 = torch.randn(2,5)
print(first_1)

tensor([[-1.0565, -0.6244,  1.6088,  0.7372,  0.4203],
        [ 0.9383, -0.5633,  0.3877,  1.1802, -1.0301]])


In [22]:
second_1 = torch.randn(3,5)
print(second_1)

tensor([[ 0.2751, -0.0090, -1.1847,  0.4444, -0.5126],
        [ 0.2733, -0.2278, -1.0138, -1.9171,  0.1071],
        [ 0.5107, -1.4168,  0.6071,  1.5763,  1.1490]])


In [25]:
con_1 = torch.cat([first_1, second_1])
print(con_1)

tensor([[-1.0565, -0.6244,  1.6088,  0.7372,  0.4203],
        [ 0.9383, -0.5633,  0.3877,  1.1802, -1.0301],
        [ 0.2751, -0.0090, -1.1847,  0.4444, -0.5126],
        [ 0.2733, -0.2278, -1.0138, -1.9171,  0.1071],
        [ 0.5107, -1.4168,  0.6071,  1.5763,  1.1490]])


In [27]:
first_2 = torch.randn(2, 3)
second_2 = torch.randn(2, 5)
print(first_2)
print(second_2)
con_2 = torch.cat([first_2, second_2], 1)
print(con_2)

tensor([[-0.4898, -1.4732, -0.1414],
        [-1.9808,  1.5344, -1.6234]])
tensor([[-0.8805, -1.1223,  0.7961, -0.5919,  0.4083],
        [ 1.7765, -0.8222, -1.8660,  0.0461,  0.8482]])
tensor([[-0.4898, -1.4732, -0.1414, -0.8805, -1.1223,  0.7961, -0.5919,  0.4083],
        [-1.9808,  1.5344, -1.6234,  1.7765, -0.8222, -1.8660,  0.0461,  0.8482]])


In [35]:
tensor_1 = torch.tensor([1,2 ,3,4])
tensor_a = torch.unsqueeze(tensor_1, 0)
print(tensor_a)
print(tensor_a.shape)
tensor_b = torch.unsqueeze(tensor_1, 1)
print(tensor_b)
print(tensor_b.shape)
tensor_2 = torch.rand(2, 3,4)
tensor_c = tensor_2[:, :, 2]
print(tensor_2)
print(tensor_c)
pri
nt(tensor_c.shape)
tensor_d =  torch.unsqueeze(tensor_c, 2)
print(tensor_d)
print(tensor_d.shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])
tensor([[[0.5887, 0.3138, 0.6378, 0.4035],
         [0.5643, 0.8597, 0.4817, 0.1366],
         [0.7362, 0.3447, 0.3847, 0.8644]],

        [[0.3538, 0.0762, 0.5913, 0.1759],
         [0.0620, 0.1555, 0.1214, 0.5054],
         [0.4882, 0.4690, 0.2503, 0.4210]]])
tensor([[0.6378, 0.4817, 0.3847],
        [0.5913, 0.1214, 0.2503]])
torch.Size([2, 3])
tensor([[[0.6378],
         [0.4817],
         [0.3847]],

        [[0.5913],
         [0.1214],
         [0.2503]]])
torch.Size([2, 3, 1])


In [37]:
x = torch.tensor([1., 2., 3], requires_grad=True)
y = torch.tensor([4., 5, 6], requires_grad=True)
z = x + y

In [38]:
print(z)

tensor([5., 7., 9.], grad_fn=<ThAddBackward>)


In [39]:
s = z.sum()
s.backward()
print(x.grad)

tensor([1., 1., 1.])


In [40]:
x = torch.randn(2,2)
print(x.requires_grad)

False


In [42]:
x.requires_grad_()
print(x.requires_grad)

True


In [46]:
x.requires_grad

True

In [47]:
(x+10).requires_grad

True

In [48]:
with torch.no_grad():
    print((x+10).requires_grad)

False


In [50]:
torch.no_grad()

In [51]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3
print(x.grad)

None


In [52]:
out = z.mean()
print(out)

tensor(27., grad_fn=<MeanBackward1>)


In [53]:
out.backward()

In [60]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])