In [1]:
import torch, torchvision

In [4]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x)
print(y)
print(z)

tensor([[-0.4179,  0.0696,  0.8800, -0.7345],
        [-1.1647,  0.4911, -1.5917, -0.9759],
        [ 0.0176, -0.0878,  0.7068,  1.5677],
        [-0.2214, -1.2107,  1.0637, -0.4538]])
tensor([-0.4179,  0.0696,  0.8800, -0.7345, -1.1647,  0.4911, -1.5917, -0.9759,
         0.0176, -0.0878,  0.7068,  1.5677, -0.2214, -1.2107,  1.0637, -0.4538])
tensor([[-0.4179,  0.0696,  0.8800, -0.7345, -1.1647,  0.4911, -1.5917, -0.9759],
        [ 0.0176, -0.0878,  0.7068,  1.5677, -0.2214, -1.2107,  1.0637, -0.4538]])


In [32]:
x = torch.randn(3, requires_grad=True)
print(x)
y = x * 2

tensor([-0.6933,  0.1126,  0.3913], requires_grad=True)


In [33]:
i = 0
while y.data.norm() < 100:
    y = y * 2
    i+= 1

print(x)
print(y)
print(i)

tensor([-0.6933,  0.1126,  0.3913], requires_grad=True)
tensor([-88.7455,  14.4082,  50.0871], grad_fn=<MulBackward>)
6


In [34]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)
print(x.grad)

tensor([ 12.8000, 128.0000,   0.0128])
